# config.yaml

# Combine
file_dir: "../result/xlsx"

# Cluster Center
n_cluster: 9
leaf_label_col: "Pistachio_Index"
[[rgb_cols]]: "Status Color"
weights: null
qtl: null
add_noise: true
drop_duplicates: false
plot_dendogram: true
cluster_center_method: "random"

# Run Experiment settings
response_col: "Pistachio_Index"
n_samples: 500
alpha: 0.1
sigf_col:
  - "min_se_sigf"
  - "ent(Y|x) < ent(Y)"
not_pred_cols:
  - "Pistachio_Index"
  - "Status"
  - "Status Color"
img_file_type:
  - "jpg"
  - "png"
img_save_type: "png"
spreadsheet_file_type: "xlsx"
filter_response: false
valid_response_list: null
verbose: false
show_all_labels: false
only_sigf: true
generate_files_only: false
do_summary: true

